language: python
python:
#   - "2.6"
   - "2.7"
#   - "3.2"
#   - "3.3"
#   - "3.4"
install:
   - pip install SQLAlchemy pycrypto

script:
   - protocol/Protocol.py
   - ./server.py &
   - sleep 30 # wait for server to start up
   - ./TestLobbyClient.py
   - sleep 10 # give server some time to write log, etc
   - killall python
